### PR TITLE
Simplify/improve wrapping of error messages.

### LINKED ISSUE #449: Warning message width is "shortened"
Steps to reproduce:
1. Add both `volta` and `toolchain` properties in package.json
2. Run `node -v` and see "shortened" warning

Screen Shot 2019-05-20 at 10 26 10 PM

Expected:

Warning message should not "shortened"

### PR DESCRIPTION
**Pull request by chriskrycho**
Resolves #449.

<details><summary>initially 80-wide terminal</summary>
term-at-80
</details>

<details><summary>initially 80-wide terminal, then resize to 100-wide terminal</summary>
80-term-back-to-100
</details>

<details><summary>initially 80-wide terminal, then resize to full screen width</summary>
80-term-full-width
</details>

<details><summary>100-wide terminal</summary>
100-terminal
</details>

<details><summary>initially 100-wide terminal, then resize to full screen width</summary>
100-resized
</details>

<details><summary>initially 100-wide terminal, then resize to 80-wide terminal</summary>
100-squished-to-80
</details>

<details><summary>120-wide terminal</summary>
120-term
</details>

<details><summary>initially 120-wide terminal, then resize to 80-wide terminal</summary>
120-term-to-80
</details>

### CODE REVIEW

**Comment by rwjblue** [comment]
@chriskrycho - Would you mind including some prose description of what this is doing (for those of us that are horrid at reading Rust)? _Possibly_ also a screenshot at a few different terminal widths?

**Comment by chriskrycho** [comment]
Screenshots!

<details><summary>initially 80-wide terminal</summary>
term-at-80
</details>

<details><summary>initially 80-wide terminal, then resize to 100-wide terminal</summary>
80-term-back-to-100
</details>

<details><summary>initially 80-wide terminal, then resize to full screen width</summary>
80-term-full-width
</details>

<details><summary>100-wide terminal</summary>
100-terminal
</details>

<details><summary>initially 100-wide terminal, then resize to full screen width</summary>
100-resized
</details>

<details><summary>initially 100-wide terminal, then resize to 80-wide terminal</summary>
100-squished-to-80
</details>

<details><summary>120-wide terminal</summary>
120-term
</details>

<details><summary>initially 120-wide terminal, then resize to 80-wide terminal</summary>
120-term-to-80
</details>

**Comment by rwjblue** [comment]
Thank you @chriskrycho!

**Comment by rwjblue** [comment]
I think this is definitely an improvement :D 🎉

**Pull request merged**
