### PR TITLE
chore: upgrade console, indicatif to avoid building parking_lot entirely

### PR DESCRIPTION
**Pull request by joshuarli**
As mentioned [here](https://github.com/volta-cli/volta/issues/536#issuecomment-605544475), you can avoid building `parking_lot` entirely if you upgrade console, indicatif, and reqwest.

Since reqwest has been swapped out in https://github.com/volta-cli/volta/pull/733 (this PR builds on top of that) and the new stuff doesn't require it, this is now possible. Honestly it's not really that much more to build, but it is completely unnecessary.

Also @charlespierce, it looks like the lockfile is stale, so feel free to cherry-pick e9599ce and see if you get any improvements there too? Here are some cargo trees you can reproduce:

before regeneration (5af6691): https://gist.github.com/joshuarli/9bb2968b764e7a747a78b6697faae39b

after (e9599ce): https://gist.github.com/joshuarli/9289bcbcf5233b93fa7701fbe9faa925

after upgrade (8fb6e2d): https://gist.github.com/joshuarli/7a973b26a518c33de45a040ad3a79bb1

### CODE REVIEW

**Comment by charlespierce** [comment]
This is awesome, thanks @joshuarli! Especially for the extra context around the lock file and the trees in different states.

**Comment by joshuarli** [comment]
Builds are definitely a bit faster. Looks like bumping that stuff broke windows, it might be solved by bumping further, lol.

**Comment by joshuarli** [comment]
Great, looks like that did it.

**Comment by charlespierce** [comment]
@joshuarli Out of curiosity, what commands did you use to update the lock file and for generating those trees? The tree especially seems super useful to understand the state of dependencies (and compare when making changes).

**Comment by joshuarli** [comment]
> @joshuarli Out of curiosity, what commands did you use to update the lock file and for generating those trees? The tree especially seems super useful to understand the state of dependencies (and compare when making changes).

`cargo generate-lockfile` and `cargo-tree tree --no-dev-dependencies`.

https://github.com/sfackler/cargo-tree

**Comment by joshuarli** [comment]
@charlespierce Merged my branch with upstream, and regenerated the lockfile.

Upstream master's lockfile seems like it's still pretty stale; lots of transient stuff is being upgraded here. Let me see if I can get you a smaller diff.

**Comment by joshuarli** [comment]
There we go, that's a much saner diff... seems `generate-lockfile` will attempt to refresh as much as possible (people like to range pin), whereas `cargo-tree tree --no-dev-dependencies` did a much more gentle refresh.

**Comment by charlespierce** [comment]
LGTM, though I'd like to confirm the CI is passing. Going to try to close and re-open to get it to start again.

**Comment by charlespierce** [comment]
Hmm, the empty commit did it, not sure why it was failing 🤷

**Comment by charlespierce** [comment]
Looks like the `console` crate has a misstated dependency (it relies on `winapi-util 0.1.3`, not `0.1.2`). I'll make a PR into that crate since it appears that we have exactly `winapi-util 0.1.2` pinned in Cargo.lock.

**Comment by charlespierce** [comment]
Oh, it looks like they just detected and fixed it today: https://github.com/mitsuhiko/console/pull/64

But it hasn't yet been released on Crates.io. We'll probably have to wait for that, and then pull in the updated version.

**Comment by joshuarli** [comment]
@charlespierce Thanks for looking into that!

**Comment by charlespierce** [comment]
@joshuarli Looks like `console` version 0.11.3 has been published now, with the fixed dependency.

**Comment by joshuarli** [comment]
@charlespierce Thanks for the heads up, things look good now.

**Comment by joshuarli** [comment]
@charlespierce I'd recommend squash merging in the future, master looks kinda ugly now haha.

**Pull request merged**
