### PR TITLE
Ensure prefix subdirectories are created when installing

### LINKED ISSUE #857: Can't install packages with npm@7  and Volta 0.9
Hi,

I just upgraded to the latest 0.9 and I can't install packages anymore 😞 

```
volta install netlify-cli
error: Could not install package 'netlify-cli'

Please confirm the package is valid and run with `--verbose` for more diagnostics.
[verbose] Installing netlify-cli with command: "npm" "install" "--global" "--loglevel=warn" "--no-update-notifier" "--no-audit" "netlify-cli"
[verbose] [install stderr]
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /Users/frank/.volta/tmp/.tmpO1Zq9R/lib
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/frank/.volta/tmp/.tmpO1Zq9R/lib'
npm ERR! enoent This is related to npm not being able to find a file.
```

I get the same error when i run `npm install --global`.

It was working perfectly before, is there some node/npm config to check here?

```
which node
/Users/frank/.volta/bin/node

```

Thanks

### PR DESCRIPTION
**Pull request by charlespierce**
Closes #857 

Info
-----
* There is an upstream bug in `npm@7` where global installs into a custom prefix will fail if the expected `lib` subdirectory doesn't already exist (https://github.com/npm/cli/issues/2012)
* While this will likely get fixed, we can also work around it internally in Volta by ensuring the expected `lib` and `bin` directories are created before running an install.

Changes
-----
* Updated the creation of the staging directory to ensure that the appropriate `lib` and `bin` directories are also created.

Tested
-----
* Confirmed that installing packages under npm 7 works as expected.

### CODE REVIEW

**Review by dherman — APPROVED** [review]
LGTM! :shipit:

**Review by rwjblue — APPROVED** [review]
Thanks for picking this up so quickly!

**Comment by DirtyF** [comment]
It still tails with some packages like gatbsy-cli:

```
➜ volta -v
0.9.1

➜ volta list --format=plain
package @11ty/eleventy@0.11.0 / eleventy / node@12.19.0 npm@built-in (default)
package gatsby-cli@2.12.111 / gatsby / node@12.19.0 npm@built-in (default)
package lerna@3.22.1 / lerna / node@12.19.0 npm@built-in (default)
package netlify-cli@2.65.7 / ntl, netlify / node@12.19.0 npm@built-in (default)
package tailwindcss@1.9.5 / tailwind, tailwindcss / node@12.19.0 npm@built-in (default)

➜ volta install lerna
success: installed lerna@3.22.1 with executables: lerna

➜ volta install vuepress
success: installed vuepress@1.7.1 with executables: vuepress

➜ volta install gatsby-cli
error: Could not install package 'gatsby-cli'

Please confirm the package is valid and run with `--verbose` for more diagnostics.

~ took 16s
➜ volta uninstall gatsby-cli
Removed executable 'gatsby' installed by 'gatsby-cli'
success: package 'gatsby-cli' uninstalled

~ took 6s
➜ volta install gatsby-cli
error: Could not install package 'gatsby-cli'

Please confirm the package is valid and run with `--verbose` for more diagnostics.
```

**Comment by charlespierce** [comment]
Hi @DirtyF, that looks like it may be a bug internally in `npm@7` or in `gatsby-cli`: When I run `npm i -g gatsby-cli` I get:

```
$ npm i -g gatsby-cli
npm ERR! Cannot read property 'matches' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cpierce/.npm/_logs/2020-10-22T19_29_58_338Z-debug.log
```
Which is a JS type error, not something Volta can work around unfortunately. Confirmed that:

- Installing `gatsby-cli` with `npm@6` works as expected
- Installing `gatsby-cli` with `npm@7` while bypassing Volta's custom behavior _also_ fails.

So my guess is it's a separate, unrelated bug within `npm@7`

**Comment by DirtyF** [comment]
Righr, and you can easily switch from npm@7  to npm@6 with Volta ⚡ 

```
volta install npm@6
success: installed and set npm@6.14.8 as default

volta install gatsby-cli@2
success: installed gatsby-cli@2.12.111 with executables: gatsby
```

**Pull request merged**
